# Generated by Django 5.0 on 2023-12-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.CharField(default=123, max_length=500),
            preserve_default=False,
        ),
    ]
